version: '3'

services:
  dataBaseMysql:   
    image: mysql:5.7.29
    container_name: mysqlDataBase
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "dataBase"
    ports:
      - "8338:3306"
    expose:
      - "3306"  
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/mysqlconfig/my.cnf:/etc/mysql/conf.d/my.cnf"
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge
    
volumes:
  dabaseMysql: 
    driver: local         